version: '3'
services:
  reverse-proxy:
    image: nginx:1.21.3
    container_name: reverse_proxy
    restart: on-failure
    depends_on:
      - frontend
      - backend
      - mysql
    volumes:
      - /home/int222/nginx/data:/usr/share/nginx/html:rw
      - /home/int222/nginx/config/nginx.conf:/etc/nginx/nginx.conf/:rw
      - /home/int222/nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
      - /home/int222/nginx/logs:/var/log/nginx/:rw
      - /home/int222/nginx/ssl:/ssl/:rw
    ports:
      - "80:80"
      - "443:443"
    networks:
      project:
        ipv4_address: 172.23.40.4
  mysql:
    image: mysql/mysql-server:8.0.26
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PSW}
    ports:
      - '3306:3306'
    volumes:
      - ./database/sql/Create_Table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/sql/Data_Insert.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      project:
        ipv4_address: 172.23.30.3
  backend:
    image: varotsk137/my_springboot:latest
    restart: on-failure
    container_name: backend
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DB_PSW}
      SERVER_FE_IP_ADDR: ${SERVER_FE_IP_ADDR}
      SERVER_FE_PORT: ${SERVER_FE_PORT}
      JWT_TOKEN_SECRET: ${INT222_JWT_SECRET}
    networks:
      project:
        ipv4_address: 172.23.20.2
  frontend:
    image: varotsk137/int222-vue3:latest
    restart: on-failure
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      project:
        ipv4_address: 172.23.10.1
networks:
  project:
    external:
      name: int222_project